Update spinner

diff --git a/devbox/setup/autojump b/devbox/setup/autojump
--- a/devbox/setup/autojump
+++ b/devbox/setup/autojump
@@ -12,7 +12,7 @@ spin() {
     after_msg="$2"
   local spinner
   local -a spinners
-  spinners=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
+  spinners=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
 
   # hide cursor
   tput civis
@@ -54,7 +54,8 @@ execute() {
       errors+=("$2")
       shift
       ;;
-    -* | --*)
+    -*)
+      echo "Invalid option: $1" >&2
       return 1
       ;;
     *)
@@ -66,7 +67,7 @@ execute() {
 
   {
     for arg in "${args[@]}"; do
-      ${~${=arg}} &>$ERROR_FILE
+      eval "$arg" &>$ERROR_FILE
       # When an error causes
       if [[ $status -ne 0 ]]; then
         # error mssages
@@ -91,7 +92,7 @@ execute() {
 
   if [[ $status -ne 0 ]]; then
     printf "\033[2K" 2>/dev/null
-    printf "\n $fg[yellow]\U26A0$reset_color  Error occurred, check the log for more information.\n" 2>/dev/null
+    printf "\n $fg[yellow]\U26A0$reset_color  Error occurred, check the log below for more information.\n" 2>/dev/null
     cat $ERROR_FILE
     exit 1
   fi
diff --git a/devbox/setup/snipkit b/devbox/setup/snipkit
--- a/devbox/setup/snipkit
+++ b/devbox/setup/snipkit
@@ -4,6 +4,7 @@ autoload -Uz colors
 colors
 
 typeset TMPFILE="/tmp/snipkit-install-$$$RANDOM"
+typeset ERROR_FILE="/tmp/snipkit-install-$$$RANDOM"
 
 spin() {
   local \
@@ -11,7 +12,7 @@ spin() {
     after_msg="$2"
   local spinner
   local -a spinners
-  spinners=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
+  spinners=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
 
   # hide cursor
   tput civis
@@ -53,7 +54,8 @@ execute() {
       errors+=("$2")
       shift
       ;;
-    -* | --*)
+    -*)
+      echo "Invalid option: $1" >&2
       return 1
       ;;
     *)
@@ -65,7 +67,7 @@ execute() {
 
   {
     for arg in "${args[@]}"; do
-      ${~${=arg}} &>/dev/null
+      eval "$arg" &>$ERROR_FILE
       # When an error causes
       if [[ $status -ne 0 ]]; then
         # error mssages
@@ -90,31 +92,25 @@ execute() {
 
   if [[ $status -ne 0 ]]; then
     printf "\033[2K" 2>/dev/null
-    printf "Oops \U2620 ... Try again!\n" 2>/dev/null
+    printf "\n $fg[yellow]\U26A0$reset_color  Error occurred, check the log below for more information.\n" 2>/dev/null
+    cat $ERROR_FILE
     exit 1
   fi
 }
 
-install() {
-  echo 'deb [trusted=yes] https://apt.fury.io/lemoony/ /' | tee /etc/apt/sources.list.d/snipkit.list
-  sudo apt-get update
-  sudo apt-get install -yq --no-install-recommends snipkit
-  return
-}
-
 execute \
-  --title \
-  "Adding source" \
+  --title "Adding source" \
+  --error "Failed to add source" \
   "echo 'deb [trusted=yes] https://apt.fury.io/lemoony/ /' | tee /etc/apt/sources.list.d/snipkit.list"
 
 execute \
-  --title \
-  "Updating package manager" \
+  --title "Updating package manager" \
+  --error "Failed to update package manager" \
   "sudo apt-get update"
 
 execute \
-  --title \
-  "Installing snipkit" \
+  --title "Installing snipkit" \
+  --error "Failed to install snipkit" \
   "sudo apt-get install -yq --no-install-recommends snipkit"
 
 printf " All processes are successfully completed \U1F389\n"
